import { LogoMark } from '../../brand/Logo'
import { Sheet } from '../../reports/Sheet'
import type { ScopeRow } from '../../../lib/api/generalReports'
import type { ReportConfig, ReportSectionId } from '../../../lib/general/reportConfig'
import { SECTION_LABELS } from '../../../lib/general/reportConfig'
import { mergePeople, onlyProject, rangeForecast, seriesPercent, sumSummary } from '../../../lib/general/reportData'
import { reportNarrative } from '../../../lib/general/reportNarrative'
import { dayOf, rangeLabel } from '../../../lib/general/reportRange'
import type { DayRange } from '../../../lib/general/reportRange'
import { LATE_KINDS } from '../../../lib/general/history'
import type { ReportData, ReportPart } from '../../../hooks/useGeneralReport'
import {
  Activity,
  Commits,
  ForecastBlock,
  Kpis,
  Narrative,
  People,
  Progress,
  ProjectComparison,
  Reviews,
  Section,
  Status,
  Tasks,
  TimeLogs,
} from './ReportSections'
import { day, moment } from './format'

type Props = {
  config: ReportConfig
  spaceName: string
  projects: ScopeRow[]
  range: DayRange
  prevRange: DayRange
  data: ReportData
  loading: Set<ReportPart>
  errors: Partial<Record<ReportPart, string>>
  generatedBy: string
  generatedAt: Date
  historySince: string | null
  onRetry: () => void
  onMoreActivity: () => void
  moreLoading: boolean
}

/** Which enabled sections a block shows, in the document's order. */
const ORDER: ReportSectionId[] = [
  'summary', 'narrative', 'progress', 'status', 'forecast', 'projectComparison',
  'people', 'activity', 'tasks', 'timeLogs', 'commits', 'reviews',
]

/**
 * The paper: letterhead, then each enabled section for the whole report, then
 * — for a space — one chapter per project repeating them for that project
 * alone. Every section reads from rows already fetched and filters them by
 * project, so a chapter costs no extra requests.
 */
export function ReportDocument(p: Props) {
  const { config, projects, range } = p
  const space = config.scope === 'space'
  const selfOnly = projects.length > 0 && projects.every((x) => !x.is_lead)
  const someSelfOnly = !selfOnly && projects.some((x) => !x.is_lead)
  const withPoints = projects.some((x) => x.points_enabled)
  const subject = space
    ? projects.length === 1 ? projects[0].name : `${projects.length} projects`
    : projects[0]?.name ?? 'Project'
  const title = config.title || (space ? `${p.spaceName} report` : `${subject} report`)
  const enabled = ORDER.filter((id) => config.sections[id] && (id !== 'projectComparison' || space))
  const nameOf = (id: string) => projects.find((x) => x.project_id === id)?.name ?? 'A project'
  const gap = p.historySince && range.from < dayOf(new Date(p.historySince)) ? day(p.historySince) : null

  const letterhead = (
    <header className="border-b border-line-strong pb-5">
      <div className="flex items-start justify-between gap-4">
        <div className="flex items-center gap-3">
          <LogoMark size={40} tone="brand" />
          <div>
            <p className="font-display text-[15px] leading-tight font-semibold text-ink">Collabify</p>
            <p className="eyebrow text-[11px] text-faint print:text-[8pt]">{p.spaceName}</p>
          </div>
        </div>
        <p className="text-right text-[12px] leading-relaxed text-muted print:text-[8pt]">
          Generated by {p.generatedBy}
          <br />
          {moment(p.generatedAt.toISOString())}
        </p>
      </div>
      <h1 className="mt-6 font-display text-[30px] leading-9 font-semibold text-balance text-ink print:text-[20pt]">{title}</h1>
      <p className="mt-2 text-[13px] text-muted print:text-[9pt]">
        {space ? projects.map((x) => x.name).join(' · ') : subject}
      </p>
      <p className="eyebrow mt-2 text-[11px] text-faint print:text-[8pt]">
        {rangeLabel(range)}
        {config.compare && <> · compared with {rangeLabel(p.prevRange)}</>}
        {config.includeArchived && <> · archived work included</>}
      </p>
      {(selfOnly || someSelfOnly) && (
        <p className="mt-4 rounded-lg surface-sunken px-3 py-2 text-[13px] text-ink">
          {selfOnly
            ? 'This report shows your own work. Owners and Managers see everyone.'
            : 'For projects marked “Your work only”, this report shows your own work. Owners and Managers of those projects see everyone.'}
        </p>
      )}
    </header>
  )

  const footer = (
    <p className="flex flex-wrap justify-between gap-2 text-[12px] text-faint print:text-[8pt]">
      <span>Collabify · {p.spaceName}</span>
      <span>
        Generated by {p.generatedBy}, {moment(p.generatedAt.toISOString())}
      </span>
    </p>
  )

  const showToc = space || enabled.length > 3

  return (
    <Sheet title="" subject="" letterhead={letterhead} footerNote={footer} id="general-report">
      {showToc && (
        <div role="navigation" aria-label="Contents" className={`text-[13px] ${space ? '' : 'print:hidden'}`}>
          <p className="eyebrow text-[11px] text-muted">Contents</p>
          <ol className="mt-2 grid gap-1 sm:grid-cols-2">
            {enabled.map((id) => (
              <li key={id}>
                <a href={`#s-all-${id}`} className="text-navy-600 hover:underline dark:text-navy-200">{SECTION_LABELS[id]}</a>
              </li>
            ))}
            {space &&
              projects.map((x) => (
                <li key={x.project_id}>
                  <a href={`#chapter-${x.project_id}`} className="text-navy-600 hover:underline dark:text-navy-200">
                    Chapter: {x.name}
                  </a>
                </li>
              ))}
          </ol>
        </div>
      )}

      <Block {...p} projectId={null} enabled={enabled} withPoints={withPoints} selfOnly={selfOnly} nameOf={nameOf} gap={gap} />

      {space &&
        projects.map((x) => (
          <div key={x.project_id} id={`chapter-${x.project_id}`} className="report-chapter scroll-mt-24 pt-8">
            <p className="eyebrow text-[11px] text-faint">Chapter</p>
            <h2 className="font-display text-[24px] leading-8 font-semibold text-ink">
              {x.name}
              {!x.is_lead && <span className="ml-2 align-middle text-[12px] font-normal text-muted">Your work only</span>}
            </h2>
            <Block
              {...p}
              projectId={x.project_id}
              enabled={enabled.filter((id) => id !== 'projectComparison')}
              withPoints={x.points_enabled}
              selfOnly={!x.is_lead}
              nameOf={nameOf}
              gap={gap}
            />
          </div>
        ))}
    </Sheet>
  )
}

function Block({
  config,
  projects,
  data,
  loading,
  errors,
  range,
  generatedAt,
  generatedBy,
  onRetry,
  onMoreActivity,
  moreLoading,
  projectId,
  enabled,
  withPoints,
  selfOnly,
  nameOf,
  gap,
}: Props & {
  projectId: string | null
  enabled: ReportSectionId[]
  withPoints: boolean
  selfOnly: boolean
  nameOf: (id: string) => string
  gap: string | null
}) {
  const key = projectId ?? 'all'
  const totals = sumSummary(onlyProject(data.summary, projectId))
  const prevTotals = data.prevSummary ? sumSummary(onlyProject(data.prevSummary, projectId)) : undefined
  const people = mergePeople(onlyProject(data.people, projectId))
  const series = seriesPercent(onlyProject(data.series, projectId), withPoints)
  const prevSeries = data.prevSeries ? seriesPercent(onlyProject(data.prevSeries, projectId), withPoints) : undefined
  const one = projectId ? projects.find((x) => x.project_id === projectId) : projects.length === 1 ? projects[0] : null
  const endsOn = one?.ends_on ?? null
  const counts = seriesPercent(onlyProject(data.series, projectId), false)
  const forecast = rangeForecast(counts, endsOn, generatedAt.getTime())
  const activity = onlyProject(data.activity, projectId)
  const activityTotal = projectId ? activity.length : data.activity?.[0]?.total ?? 0
  const reviews = onlyProject(data.reviews, projectId)
  const top = [...people].sort((a, b) => b.tasks_finished_in_range - a.tasks_finished_in_range)[0]
  const empty = `Nothing happened in ${rangeLabel(range)}.`
  const busy = (part: ReportPart) => loading.has(part) && !data[part]
  const err = (part: ReportPart) => errors[part]
  const id = (s: ReportSectionId) => `s-${key}-${s}`

  const lines =
    data.summary
      ? reportNarrative({
          totals,
          previous: prevTotals ?? null,
          top: !selfOnly && top?.name ? { name: top.name, finished: top.tasks_finished_in_range } : null,
          self: selfOnly,
          forecast: config.sections.forecast ? forecast : null,
          reviewsWaiting: data.reviews ? reviews.filter((r) => r.status === 'open').length : undefined,
        })
      : []

  const comparison = projects.map((x) => {
    const pp = onlyProject(data.people, x.project_id)
    const last = pp.reduce<string | null>((m, r) => (r.last_activity && (!m || r.last_activity > m) ? r.last_activity : m), null)
    return { project: x, totals: sumSummary(onlyProject(data.summary, x.project_id)), lastActivity: last }
  })

  return (
    <div className="mt-6 space-y-8">
      {enabled.map((s) => {
        switch (s) {
          case 'summary':
            return (
              <Section key={s} id={id(s)} title="Key figures" loading={busy('summary')} error={err('summary')} onRetry={onRetry} emptyText={empty}>
                <Kpis totals={totals} previous={prevTotals} />
              </Section>
            )
          case 'narrative':
            return (
              <Section key={s} id={id(s)} title="Summary" loading={busy('summary')} error={err('summary')} onRetry={onRetry} emptyText={empty}>
                <Narrative lines={lines} note={projectId ? undefined : config.note} noteBy={generatedBy} />
              </Section>
            )
          case 'progress':
            return (
              <Section key={s} id={id(s)} title="Progress over time" loading={busy('series')} error={err('series')} onRetry={onRetry}
                empty={series.every((x) => x.total === 0)} emptyText={empty}>
                <Progress
                  points={series}
                  previous={prevSeries}
                  todayDay={dayOf(generatedAt)}
                  endDay={endsOn}
                  usingPoints={withPoints}
                />
              </Section>
            )
          case 'status':
            return (
              <Section key={s} id={id(s)} title="Task status" loading={busy('summary')} error={err('summary')} onRetry={onRetry}
                empty={totals.tasks_total === 0} emptyText="There are no tasks here yet.">
                <Status totals={totals} />
              </Section>
            )
          case 'forecast':
            return (
              <Section key={s} id={id(s)} title="Forecast" loading={busy('series')} error={err('series')} onRetry={onRetry} emptyText={empty}>
                <ForecastBlock forecast={forecast} />
              </Section>
            )
          case 'projectComparison':
            return (
              <Section key={s} id={id(s)} title="Project comparison" loading={busy('summary') || busy('people')}
                error={err('summary') ?? err('people')} onRetry={onRetry} empty={projects.length === 0} emptyText="No projects are in this report.">
                <ProjectComparison rows={comparison} />
              </Section>
            )
          case 'people':
            return (
              <Section key={s} id={id(s)} title={selfOnly ? 'Your work' : 'Who did what'} loading={busy('people')} error={err('people')}
                onRetry={onRetry} empty={people.length === 0} emptyText={empty}>
                <People rows={people} withPoints={withPoints} score={config.sections.score && !selfOnly ? config.score : null} />
              </Section>
            )
          case 'activity':
            return (
              <Section key={s} id={id(s)} title="Activity" loading={busy('activity')} error={err('activity')} onRetry={onRetry}
                empty={activity.length === 0} emptyText={empty}>
                {gap && (
                  <p className="mb-3 text-[12px] text-faint">
                    Archiving and membership changes are recorded from {gap}.
                    {config.activityKinds.some((k) => LATE_KINDS.includes(k)) ? ' Earlier ones do not appear.' : ''}
                  </p>
                )}
                <Activity
                  rows={activity}
                  total={activityTotal}
                  groupBy={config.groupActivityBy}
                  projectName={nameOf}
                  onMore={projectId ? undefined : onMoreActivity}
                  moreLoading={moreLoading}
                />
              </Section>
            )
          case 'tasks':
            return (
              <Section key={s} id={id(s)} title="Tasks" loading={busy('tasks')} error={err('tasks')} onRetry={onRetry}
                empty={onlyProject(data.tasks, projectId).length === 0} emptyText={empty}>
                <Tasks rows={onlyProject(data.tasks, projectId)} withPoints={withPoints} />
              </Section>
            )
          case 'timeLogs':
            return (
              <Section key={s} id={id(s)} title="Time logs" loading={busy('timeLogs')} error={err('timeLogs')} onRetry={onRetry}
                empty={onlyProject(data.timeLogs, projectId).length === 0} emptyText={empty}>
                <TimeLogs rows={onlyProject(data.timeLogs, projectId)} />
              </Section>
            )
          case 'commits':
            return (
              <Section key={s} id={id(s)} title="Commits" loading={busy('commits')} error={err('commits')} onRetry={onRetry}
                empty={onlyProject(data.commits, projectId).length === 0} emptyText={empty}>
                <Commits rows={onlyProject(data.commits, projectId)} />
              </Section>
            )
          case 'reviews':
            return (
              <Section key={s} id={id(s)} title="Reviews" loading={busy('reviews')} error={err('reviews')} onRetry={onRetry}
                empty={reviews.length === 0} emptyText={empty}>
                <Reviews rows={reviews} />
              </Section>
            )
          default:
            return null
        }
      })}
    </div>
  )
}
